[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://poke-battle-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 